"""Recipe servings

Revision ID: 12096f362ad2
Revises: f1471bc70160
Create Date: 2024-04-04 14:21:58.908770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12096f362ad2'
down_revision: Union[str, None] = 'f1471bc70160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('servings', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'servings')
    # ### end Alembic commands ###
