"""Ingredients and recipes

Revision ID: 1883ac6eb22b
Revises: 516f2e855bc2
Create Date: 2022-03-14 01:05:24.286382

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '1883ac6eb22b'
down_revision = '516f2e855bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('aisle', sa.String(), nullable=False),
        sa.Column('stocked', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('ingredients_recipes',
        sa.Column('recipe', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('ingredient', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('amount', sa.Float(), nullable=True),
        sa.UniqueConstraint('recipe', 'ingredient', name='recipe_ingredient_key')
    )
    op.create_table('recipes',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    op.drop_table('ingredients_recipes')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
