"""List FK delete support.

Revision ID: 41ffebeb9cc3
Revises: ee7cb2e27987
Create Date: 2025-12-14 02:03:47.648486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ffebeb9cc3'
down_revision: Union[str, None] = 'ee7cb2e27987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('list_items_list_id_fkey', 'list_items', 'lists', ['list'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('list_recipes_list_id_fkey', 'lists_recipes', 'lists', ['list'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('list_recipes_list_id_fkey', 'lists_recipes', type_='foreignkey')
    op.drop_constraint('list_items_list_id_fkey', 'list_items', type_='foreignkey')
    # ### end Alembic commands ###
