"""Add citext

Revision ID: 4778f8e88575
Revises: 84f2c6f085e8
Create Date: 2024-04-04 13:35:20.504612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4778f8e88575'
down_revision: Union[str, None] = '84f2c6f085e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "citext";')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP EXTENSION IF EXISTS "citext";')
    # ### end Alembic commands ###
