"""Freezer item support

Revision ID: 6f3d05965436
Revises: f66f38318522
Create Date: 2025-07-09 22:51:00.248552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f3d05965436'
down_revision: Union[str, None] = 'f66f38318522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freezer_freshness',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', postgresql.CITEXT(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('freezer_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', postgresql.CITEXT(), nullable=False),
    sa.Column('freezer_bag_id', postgresql.CITEXT(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('freshness_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['freshness_id'], ['freezer_freshness.id'], name='freezer_items_id_freezer_freshness_id_fkey'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('freezer_bag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('freezer_items')
    op.drop_table('freezer_freshness')
    # ### end Alembic commands ###
