"""Recipe notes

Revision ID: 84f2c6f085e8
Revises: ade5ea2fe06e
Create Date: 2024-04-04 02:32:41.365717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f2c6f085e8'
down_revision: Union[str, None] = 'ade5ea2fe06e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_notes',
    sa.Column('recipe', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.UniqueConstraint('recipe', name='recipe_notes_recipe_key')
    )
    op.alter_column('list_items', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('list_items', 'amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_table('recipe_notes')
    # ### end Alembic commands ###
