"""Adding FDA records

Revision ID: 85c5bc69fd62
Revises: 6f3d05965436
Create Date: 2025-11-30 18:16:27.217275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c5bc69fd62'
down_revision: Union[str, None] = '6f3d05965436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO freezer_freshness (id, name, duration_days) VALUES
        (uuid_generate_v4(), 'Egg, raw whites and yolks, no shell', 365),
        (uuid_generate_v4(), 'Liquid pasteurized egg or substitute, unopened', 365),
        (uuid_generate_v4(), 'TV Dinners', 121),
        (uuid_generate_v4(), 'Hamburger or stew meat, raw', 121),
        (uuid_generate_v4(), 'Ground turkey, veal, pork, lamb, raw', 121),
        (uuid_generate_v4(), 'Corned beaf, in pickling juice, drained', 30),
        (uuid_generate_v4(), 'Ηam, canned, unopened, labeled "Keep Refrigerated"', 30),
        (uuid_generate_v4(), 'Ham, fully cooked, any way', 30),
        (uuid_generate_v4(), 'Hot dogs', 30),
        (uuid_generate_v4(), 'Lunch meats', 30),
        (uuid_generate_v4(), 'Soups, with or without meat', 60),
        (uuid_generate_v4(), 'Bacon', 30),
        (uuid_generate_v4(), 'Sausage, any meat, any way', 30),
        (uuid_generate_v4(), 'Beef, Veal, Lamb, Pork steaks', 180),
        (uuid_generate_v4(), 'Beef, Veal, Lamb, Pork chops', 120),
        (uuid_generate_v4(), 'Beef, Veal, Lamb, Pork roasts', 120),
        (uuid_generate_v4(), 'Beef, Veal, Lamb, Pork other organs', 120),
        (uuid_generate_v4(), 'Meat dishes, leftover', 60),
        (uuid_generate_v4(), 'Meat gravy or broth, leftover', 60),
        (uuid_generate_v4(), 'Chicken or turkey, whole', 365),
        (uuid_generate_v4(), 'Chicken or turkey, parts', 270),
        (uuid_generate_v4(), 'Giblets', 90),
        (uuid_generate_v4(), 'Chicken, fried', 120),
        (uuid_generate_v4(), 'Chicken, leftover', 120),
        (uuid_generate_v4(), 'Chicken, with gravy', 180),
        (uuid_generate_v4(), 'Chicken, nuggets or patties', 30),
        (uuid_generate_v4(), 'Lean fish', 180),
        (uuid_generate_v4(), 'Fatty fish', 60),
        (uuid_generate_v4(), 'Cooked fish', 120),
        (uuid_generate_v4(), 'Shrimp, scallops, crawfish, squid, fresh', 90),
        (uuid_generate_v4(), 'Seafood, previously canned', 60)
        '''
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
