"""Shopping list item IDs

Revision ID: 867e0b557f80
Revises: 85c5bc69fd62
Create Date: 2025-12-06 12:48:17.965282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '867e0b557f80'
down_revision: Union[str, None] = '85c5bc69fd62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_items', sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=True))
    op.execute('UPDATE list_items SET id = uuid_generate_v4();')
    op.alter_column('list_items', 'id', nullable=False)
    op.create_primary_key('list_items_id_pkey', 'list_items', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('list_items_id_pkey', 'list_items')
    op.drop_column('list_items', 'id')
    # ### end Alembic commands ###
