"""Cascade recipe deletion to notes

Revision ID: 96c026b55c6e
Revises: b460332735c3
Create Date: 2025-05-12 15:24:34.425564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c026b55c6e'
down_revision: Union[str, None] = 'b460332735c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('recipe_notes_recipe_fkey', 'recipe_notes', 'recipes', ['recipe'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_notes_recipe_fkey', 'recipe_notes', type_='foreignkey')
    # ### end Alembic commands ###
