"""Lists support

Revision ID: ade5ea2fe06e
Revises: 1883ac6eb22b
Create Date: 2024-04-03 16:15:30.504391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade5ea2fe06e'
down_revision: Union[str, None] = '1883ac6eb22b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_items',
    sa.Column('list', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aisle', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False)
    )
    op.create_table('lists',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lists_recipes',
    sa.Column('list', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scale', sa.Float(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lists_recipes')
    op.drop_table('lists')
    op.drop_table('list_items')
    # ### end Alembic commands ###
