"""CITEXT for quick item names

Revision ID: b460332735c3
Revises: f298b7e01716
Create Date: 2024-04-14 21:47:08.068785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b460332735c3'
down_revision: Union[str, None] = 'f298b7e01716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quick_items', 'name',
               existing_type=sa.VARCHAR(),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    op.alter_column('recipes', 'routine',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'routine',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('quick_items', 'name',
               existing_type=postgresql.CITEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
