"""Combined constraint for quick item insertion from lists

Revision ID: ee7cb2e27987
Revises: 867e0b557f80
Create Date: 2025-12-11 14:19:41.175741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7cb2e27987'
down_revision: Union[str, None] = '867e0b557f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('quick_items_name_key'), 'quick_items', type_='unique')
    op.create_unique_constraint('quick_items_name_aisle_key', 'quick_items', ['name', 'aisle'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quick_items_name_aisle_key', 'quick_items', type_='unique')
    op.create_unique_constraint(op.f('quick_items_name_key'), 'quick_items', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
