"""Make ingredient and recipe names citext

Revision ID: f1471bc70160
Revises: 4778f8e88575
Create Date: 2024-04-04 13:37:56.207207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1471bc70160'
down_revision: Union[str, None] = '4778f8e88575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredients', 'name',
               existing_type=sa.VARCHAR(),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    op.alter_column('recipes', 'name',
               existing_type=sa.VARCHAR(),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'name',
               existing_type=postgresql.CITEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('ingredients', 'name',
               existing_type=postgresql.CITEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
