"""Routine recipes

Revision ID: f298b7e01716
Revises: 3e9794089930
Create Date: 2024-04-09 03:16:34.731067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f298b7e01716'
down_revision: Union[str, None] = '3e9794089930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('routine', sa.Boolean(), nullable=True))
    
    op.execute('''
               UPDATE recipes SET routine = FALSE;
               ''')
    
    op.alter_column('recipes', 'routine', nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'routine')
    # ### end Alembic commands ###
